### PR TITLE
Build changes part deux

### PR DESCRIPTION
**Pull request by quasar1**
@quarnster 
Just need you to try this on OSX... I need some sleep now... :D

### CODE REVIEW

**Comment by quarnster** [comment]
You're running linux in a virtual environment, right? It _might_ actually be better to run freebsd instead as then it'll be much clearer that you are cross compiling for a different system. But do whatever seems to work and causes less pain :)

**Comment by quasar1** [comment]
i386 or amd64? Any specific version?
Just out of interest what environment do you use?

On a semi related note, for the Boxee intel sdk I'm  having issues compiling, my cmake is too old (2.8). So setting up a different virtual build env makes sense.

**Comment by quarnster** [comment]
amd64 would be even better as that is another step away from what the boxeebox uses. I'm just building directly on my macbook pro laptop, no virtual environment.

**Comment by quasar1** [comment]
So what apps do you need to build on the macbook?
I'm toying with a yosemite zone VM install or maybe a dual boot, never used OSX before.

**Comment by quarnster** [comment]
- Install [brew](http://brew.sh/) (like apt-get for osx)
- Run `brew install gcc49` in a terminal
- Check boxeebox-xbmc's [readme](https://github.com/quarnster/boxeebox-xbmc/blob/master/docs/README.boxeebox) for its `brew install` line and install those

If it errors out trying to install anything, you might have to install XCode via the App Store (do you have appstore access with the vm?) and then install the command line tools from inside Xcode. I think you just have to open up xcode and go to preferences or something to find that option, don't recall of the top of my head.

OSX is based on FreeBSD so uses BSD versions instead of gnu versions of some programs. That's the reason you have to `brew install gnu-sed` and do:

``` sh
ln -s /usr/local/bin/gsed sed
export PATH=$PWD:$PATH
```

so that gnu-sed is used instead of bsd-sed for example. Also as clang is default on OSX you have to do:

``` sh
export CC=/usr/local/bin/gcc-4.9
export CXX=/usr/local/bin/g++-4.9
export CPP=/usr/local/bin/cpp-4.9
export LD=/usr/local/bin/gcc-4.9
```

so that it uses gcc instead.

Using FreeBSD is probably similar in that department, with the major difference being that instead of `brew` whatever package-manager FreeBSD uses nowadays is used instead. 

Also I personally like [iTerm2](https://www.iterm2.com/) instead of the standard terminal program, but that's optional.

**Comment by quasar1** [comment]
Well yosemite zone on Oracle Virtual Box was a complete failure even after extensive customisations and jumping through hoops. Mainly due to my CPU being too new. However, on VMware workstation it installed without issue and I'm up and running with the app store currently downloading xcode.
Only time will tell if it can produce the goods without further issues. Its going to be a learning curve from here on in to find my way around OSX and the compiling stuff.
Thanks for all your information, a great help.

**Comment by quasar1** [comment]
Update:
yosemite zone was very unstable, found a Mavericks .vmdk which seems to work perfect even though I can only use 2 cores on my 4 core CPU.
Just having a go with the boxeebox-sdk, seems I need a number of additional prerequisites including 'go'. 
Might invest in a cheap Mac Mini :)

**Comment by quarnster** [comment]
Or try freebsd for free ;)

Might give a freebsd vm a go myself, it's been a really long time since I ran it and I'd like to check it out

**Comment by quasar1** [comment]
I had a brief go at freebsd the other day and hit a number of walls, thought OSX may be a bit easier getting an env which was a bit more noob friendly. I may go back to it at some point. I started with the latest version 10.1 amd64 VM image, I found it overwhelming so ditched it to try the hackintosh OSX methods and that was even more overwhelming until I found the Mavericks .vdmk. Not sure if I took the correct path, only time will tell.

**Comment by quasar1** [comment]
FYI.
Ready made FreeBSD 10.1 VM's for Virtualbox and VMWare.
http://www.osboxes.org/freebsd/

Untested.

**Pull request closed without merging**
