### PR TITLE
Netflix Button Addition

### PR DESCRIPTION
**Pull request by zang74**
Added missing key command for Netflix-Button Boxee Boxes.

### CODE REVIEW

**Comment by quasar1** [comment]
@zang74 Great work,I have uploaded a test build so you can confirm it works your end, I have tested here (I don't have the Netflix button but everything appears to work fine, no regressions).
https://www.sendspace.com/file/s6jwfa
I added the system folder too, not needed unless you want the new improved advancedsettings.xml.

**Comment by zang74** [comment]
Hi,

I’ve tested, but am getting nothing. That said, the file creation date/time of the Kodi.bin you sent is March 27th, the same as the last release. Is it possible I got the old build?

**Comment by quasar1** [comment]
@zang74 Yes looks like I packaged the wrong rar.
Try this one..
https://www.sendspace.com/file/3eda10

**Comment by zang74** [comment]
That did it! It works as expected.

**Comment by quasar1** [comment]
Great, do you mind doing the PR to quasar1 github Helix branch?
Reason being there's a lot of merge conflicts to do on this github merge as it's so far behind in commits.

**Comment by zang74** [comment]
Done.

**Comment by quasar1** [comment]
Thanks, merged on the quasar1 github.
I will update the Helix branch here when I get the subtitles fixed, IF I can find a way to do that...

**Comment by zang74** [comment]
Thanks! Wish I could be of more help. I'm no C++ coder; just a PHP guy who got tired of that damn button taunting me with its impotence and did some sleuthing.

Also; any idea how I'd get past the read-only tag to shoehorn the new binary into my internal install, or should I ask Orizzle?

**Comment by quasar1** [comment]
I'm no C++ coder, just sheer determination, dedication, trial an error and research.
So, it goes to prove it's only ones self stopping any progression.

I am not sure how the internal install works not tried it. You may be able to browse the Boxee Box  using WinSCP FTP/Putty and change the file permissions that way.

**Comment by quasar1** [comment]
@zang74 
https://github.com/quasar1/boxeebox-xbmc/releases/tag/2.3-alpha_Helix
Contains your fix plus some other enhancements.

**Comment by zang74** [comment]
Just discovered something interesting, Quasar. Apparently, Kodi is logging debug notifications _even when_ all logging is turned off in advancedsettings.xml using <loglevel>. The build is a debug build, [23:07:18 T:3038897888  NOTICE: Using Debug Kodi x32 build] and thus that logging cannot be turned off without a recompile. Apparently there was a similar issue with the Android version, and there's a thread about it here: http://forum.kodi.tv/showthread.php?tid=207278&page=1

This leads into:

I run my BBs 24/7, and I've also discovered that log files are being buffered somewhere before being written to kodi.log, as "cat /dev/null > kodi.log" will empty the log file, but within a minute the file will be re-written with all the info that was just erased. I saw this happen with an 11.6MB log file. If this is being stored in RAM, this could be an issue, and could be slowly eating RAM the longer the machine remains on, and could be causing some of the RAM issues recent builds have had. I can't see buffering ~12MB of log files an efficient use of memory.

**Comment by quasar1** [comment]
@zang74 
I'm not sure you can totally disable 'logging' altogether, and I think that's what you are implying?
Have you tried the results of doing the same settings in a Kodi 14.2 Windows final build?
I will do a test build with --enable-debug=no configure flag to find out more.

More info here:
http://forum.kodi.tv/showthread.php?tid=213190

**Comment by devil-strike** [comment]
Be aware quarnster enabled allot of logging option for video part, intel smd etc debug, think if you can disable that it will run allot better. Dont think you need it anymore(there are no devs that can fix that part of errors)

**Comment by zang74** [comment]
Apparently, in release builds one can disable logging altogether by using the loglevel tag in advancedsettings.xml. I tried this (loglevel -1) after trying loglevel 0 (just notices errors, no debug comments), only to discover that neither worked. This is apparently because the build is set as a debug build and not a release build, meaning debugging is turned on by default and turning it off is disabled. This may also be why it often creates insanely large log files without offloading to kodi.old.log. As it is now, the log file will continue to grow with every debug notice (and that includes every keypress, loading of GUI elements, etc.) with no end until the machine is rebooted.

**Comment by quasar1** [comment]
@devil-strike Yes you are absolutely right. Looks like we aren't going to get any further dev help regarding Intel SMD so must make best of what we have.
 Also some of the Kodi commits that were introduced after Gotham final to do with refclock and drop sync could be removed also. They seemed to have caused regressions, except the seek handling was a bit better. I think a new branch will be the best option, the changes will be rather invasive but we are/were in alpha stage and will always be. 

@zang74 I have just compiled a test build, I will upload it shortly for you to try.

BTW. Can someone direct Orizzle in this post http://boxeed.in/forums/viewtopic.php?f=13&t=1273 to https://github.com/quasar1/boxeebox-xbmc/issues/12

I have opened 'issues' on the quasar1 github, thanks.

**Comment by quasar1** [comment]
@zang74 
https://www.sendspace.com/file/ph0agb

**Comment by zang74** [comment]
I finally got a chance to test this version.

The debugging messaging appears to have stopped, and confluence appears markedly faster—I'm guessing because it's not having to write every GUI element load or keypress to log. Library scanning and launching of videos is slower, but I'm chalking that up to testing Kodi and its db entirely off a slow USB key (my main install is internal and I use a networked MariaDB server for the database). None of the log messages seem terribly out of the ordinary though.

**Comment by quasar1** [comment]
There's a noticeable difference even with default with just debugging off.

**Pull request closed without merging**
